spring:
  application:
    name: Notepad

  quartz:
    job-store-type: memory
    scheduler-name: test-scheduler

  datasource:
    url: jdbc:postgresql://localhost:5432/notepad_db
    username: postgres
    password: 281299
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  #Create or Upgrade the tables
    show-sql: true